### ISSUE TITLE
Only one DNS entry is being updated by the script

### ISSUE THREAD

**Issue by eibhei** [tofumatt/dynamic-dns-on-hover#2]
The script only seems to be updating the @ A entry in the hover DNS settings, but not the * A entry. I've had a quick check through the code, but my python isn't really up to scratch to change the script to be able to update both entries.

Bit of a long shot, since the script is 2 years old now, but hopefully you'll be able to help! :)

**Comment by tofumatt** [comment]
Sadly I've not used the script in awhile as a bit after I wrote it I got a router that did it for me 😉 

Sorry I don't know what's up–though if there's an error I could probably help 😄. If it's just not working I don't know what it'd be. Might be that * never worked?

**Comment by eibhei** [comment]
Haha, no problem dude! I knew it was a bit of a long shot anyway. There don't seem to be any errors, I think it's just not picking up the fact that there are 2 A records to change. I'll have a fiddle around and see if I can't fix it :)

Appreciate you leaving the script available for use though! Absolute life saver :D
